### ISSUE TITLE
Setup Tutorial

### ISSUE THREAD

**Issue by sachag678** [manageyourproject/manageyourproject#1]
Having difficulty figuring out how to actually run it.
 - Running myp in bash doesn't do anything (I have currently installed it in a docker instance so maybe that is causing issues?). 

A how-to for simple set-up would be helpful.

**Comment by sachag678** [comment]
Thanks for the how-to. (I think this is a docker issue. )

**Comment by manageyourproject** [comment]
I tried doing a fresh install on a virtual machine and was able to get it working with the installation process in the readme, but I don't have much experience with docker and so can't comment on that. I'll try it, see if I can get it to work and let you know what I find.

**Comment by decisivesacha** [comment]
It is definitely a docker issue. I have it running on my main machine.

**Comment by decisivesacha** [comment]
I think there still will need to be a tutorial?
I am getting an error when I try to add a new task to an active project. (Maybe I'm doing it wrong? Or it is broken?)

sacha@al:$ myp proj "Today"
sacha@al:$ myp task "Go to Aaron's"
Traceback (most recent call last):
  File "/home/sacha/.local/bin/myp", line 11, in <module>
    load_entry_point('myp', 'console_scripts', 'myp')()
  File "/home/sacha/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sacha/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sacha/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sacha/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sacha/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sacha/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/sacha/Repositories/manageyourproject/myp/scripts/cli.py", line 207, in task
    ctxObjs['projObj'].newTask(taskname, assignee)
AttributeError: 'projObj' object has no attribute 'newTask'

**Comment by manageyourproject** [comment]
Thanks for confirming it is a docker issue. As per the other problem that was because I forgot i had started committed some changes before branching. I've rolled the master branch back and it should all work correctly without giving errors. I'll close this issue and mark it as a problem with docker.
